@startuml
participant Actor
create GameControllerImpl
Actor -> GameControllerImpl : new
activate GameControllerImpl
create StartView
GameControllerImpl -> StartView : new
activate StartView
StartView -> StartView : λ→
activate StartView
StartView --> StartView
deactivate StartView
StartView -> StartView : λ→
activate StartView
StartView -> GameController : startGame
activate GameController
GameController -> GameControllerImpl : startGame
activate GameControllerImpl
GameControllerImpl -> GameManager : initialize
activate GameManager
GameManager -> GameManagerImpl : initialize
activate GameManagerImpl
GameManagerImpl -> GameManagerImpl : initialize
activate GameManagerImpl
GameManagerImpl -> MapFileManager : evaluateFile
activate MapFileManager
MapFileManager -> MapFileManager : λ→
activate MapFileManager
MapFileManager -> BridgeMap : makeCell
activate BridgeMap
create StartCell
BridgeMap -> StartCell : new
activate StartCell
StartCell --> BridgeMap
deactivate StartCell
BridgeMap -> Direction : getDirectionByChar
activate Direction
Direction --> BridgeMap
deactivate Direction
BridgeMap -> Direction : getDirectionByChar
activate Direction
Direction --> BridgeMap
deactivate Direction
BridgeMap -> Direction : opposite
activate Direction
Direction --> BridgeMap
deactivate Direction
create Cell
BridgeMap -> Cell : new
activate Cell
Cell --> BridgeMap
deactivate Cell
create BridgeCell
BridgeMap -> BridgeCell : new
activate BridgeCell
BridgeCell --> BridgeMap
deactivate BridgeCell
create BridgeCell
BridgeMap -> BridgeCell : new
activate BridgeCell
BridgeCell --> BridgeMap
deactivate BridgeCell
BridgeMap -> CellService : connectCell
activate CellService
CellService --> BridgeMap
deactivate CellService
BridgeMap -> CellService : connectCell
activate CellService
CellService --> BridgeMap
deactivate CellService
create CardCell
BridgeMap -> CardCell : new
activate CardCell
CardCell --> BridgeMap
deactivate CardCell
create CardCell
BridgeMap -> CardCell : new
activate CardCell
CardCell --> BridgeMap
deactivate CardCell
create CardCell
BridgeMap -> CardCell : new
activate CardCell
CardCell --> BridgeMap
deactivate CardCell
create EndCell
BridgeMap -> EndCell : new
activate EndCell
EndCell --> BridgeMap
deactivate EndCell
BridgeMap -> CellService : connectCell
activate CellService
CellService --> BridgeMap
deactivate CellService
BridgeMap -> CellService : connectCell
activate CellService
CellService --> BridgeMap
deactivate CellService
BridgeMap -> CellService : connectCell
activate CellService
CellService --> BridgeMap
deactivate CellService
BridgeMap -> Direction : getDirectionByChar
activate Direction
Direction --> BridgeMap
deactivate Direction
BridgeMap --> MapFileManager
deactivate BridgeMap
MapFileManager --> MapFileManager
deactivate MapFileManager
MapFileManager --> GameManagerImpl
deactivate MapFileManager
create Player
GameManagerImpl -> Player : new
activate Player
Player --> GameManagerImpl
deactivate Player
GameManagerImpl --> GameManagerImpl
deactivate GameManagerImpl
GameManagerImpl --> GameManager
deactivate GameManagerImpl
GameManager --> GameControllerImpl
deactivate GameManager
GameControllerImpl -> SimpleMainViewFactory : createMainView
activate SimpleMainViewFactory
SimpleMainViewFactory -> ConsoleView : getInstance
activate ConsoleView
ConsoleView --> SimpleMainViewFactory
deactivate ConsoleView
create MainFrame
SimpleMainViewFactory -> MainFrame : new
activate MainFrame
MainFrame -> GameManager : registerObserver
activate GameManager
GameManager -> GameManagerImpl : registerObserver
activate GameManagerImpl
GameManagerImpl --> GameManager
deactivate GameManagerImpl
GameManager --> MainFrame
deactivate GameManager
create MapPanel
MainFrame -> MapPanel : new
activate MapPanel
MapPanel -> Direction : values
activate Direction
Direction --> MapPanel
deactivate Direction
MapPanel -> CellService : canMove
activate CellService
CellService --> MapPanel
deactivate CellService
create Index
MapPanel -> Index : new
activate Index
Index --> MapPanel
deactivate Index
MapPanel -> Direction : values
activate Direction
Direction --> MapPanel
deactivate Direction
MapPanel -> CellService : canMove
activate CellService
CellService --> MapPanel
deactivate CellService
MapPanel -> Direction : opposite
activate Direction
Direction --> MapPanel
deactivate Direction
MapPanel -> CellService : canMove
activate CellService
CellService --> MapPanel
deactivate CellService
MapPanel -> CellService : canMove
activate CellService
CellService --> MapPanel
deactivate CellService
create Index
MapPanel -> Index : new
activate Index
Index --> MapPanel
deactivate Index
create CellPanel
MapPanel -> CellPanel : new
activate CellPanel
CellPanel --> MapPanel
deactivate CellPanel
MapPanel --> MainFrame
deactivate MapPanel
create InventoryPanel
MainFrame -> InventoryPanel : new
activate InventoryPanel
create CardPanel
InventoryPanel -> CardPanel : new
activate CardPanel
CardPanel --> InventoryPanel
deactivate CardPanel
InventoryPanel -> CardPanel : updateCard
activate CardPanel
CardPanel --> InventoryPanel
deactivate CardPanel
InventoryPanel --> MainFrame
deactivate InventoryPanel
create BottomPanel
MainFrame -> BottomPanel : new
activate BottomPanel
create ArrowButtonPanel
BottomPanel -> ArrowButtonPanel : new
activate ArrowButtonPanel
ArrowButtonPanel --> BottomPanel
deactivate ArrowButtonPanel
BottomPanel -> BottomPanel : λ→
activate BottomPanel
BottomPanel -> GameController : rollDice
activate GameController
GameController -> GameControllerImpl : rollDice
activate GameControllerImpl
GameControllerImpl -> GameManager : rollDice
activate GameManager
GameManager -> GameManagerImpl : rollDice
activate GameManagerImpl
GameManagerImpl -> Dice : roll
activate Dice
Dice --> GameManagerImpl
deactivate Dice
GameManagerImpl --> GameManager
deactivate GameManagerImpl
GameManager --> GameControllerImpl
deactivate GameManager
GameControllerImpl -> MainView : alertMessage
activate MainView
MainView --> GameControllerImpl
deactivate MainView
GameControllerImpl -> GameManager : endTurn
activate GameManager
GameManager -> GameManagerImpl : endTurn
activate GameManagerImpl
GameManagerImpl -> Player : hasWon
activate Player
Player --> GameManagerImpl
deactivate Player
GameManagerImpl --> GameManager
deactivate GameManagerImpl
GameManager --> GameControllerImpl
deactivate GameManager
GameControllerImpl -> MainView : alertMessage
activate MainView
MainView --> GameControllerImpl
deactivate MainView
GameControllerImpl --> GameController
deactivate GameControllerImpl
GameController --> BottomPanel
deactivate GameController
BottomPanel --> BottomPanel
deactivate BottomPanel
BottomPanel -> BottomPanel : λ→
activate BottomPanel
BottomPanel -> GameController : restTurn
activate GameController
GameController -> GameControllerImpl : restTurn
activate GameControllerImpl
GameControllerImpl -> GameManager : restTurn
activate GameManager
GameManager -> GameManagerImpl : restTurn
activate GameManagerImpl
GameManagerImpl -> Player : hasBridge
activate Player
Player --> GameManagerImpl
deactivate Player
GameManagerImpl -> GameManagerImpl : endTurn
activate GameManagerImpl
GameManagerImpl -> Player : hasWon
activate Player
Player --> GameManagerImpl
deactivate Player
GameManagerImpl --> GameManagerImpl
deactivate GameManagerImpl
GameManagerImpl --> GameManager
deactivate GameManagerImpl
GameManager --> GameControllerImpl
deactivate GameManager
GameControllerImpl -> MainView : alertMessage
activate MainView
MainView --> GameControllerImpl
deactivate MainView
GameControllerImpl -> MainView : alertMessage
activate MainView
MainView --> GameControllerImpl
deactivate MainView
GameControllerImpl --> GameController
deactivate GameControllerImpl
GameController --> BottomPanel
deactivate GameController
BottomPanel --> BottomPanel
deactivate BottomPanel
BottomPanel --> MainFrame
deactivate BottomPanel
MainFrame -> MapPanel : printMap
activate MapPanel
MapPanel -> CellPanel : deletePlayer
activate CellPanel
CellPanel --> MapPanel
deactivate CellPanel
MapPanel -> CellPanel : setBorder
activate CellPanel
CellPanel --> MapPanel
deactivate CellPanel
MapPanel -> CellService : moveBridge
activate CellService
CellService --> MapPanel
deactivate CellService
create Index
MapPanel -> Index : new
activate Index
Index --> MapPanel
deactivate Index
MapPanel -> CellPanel : deleteGraphics
activate CellPanel
CellPanel --> MapPanel
deactivate CellPanel
MapPanel -> CellPanel : setBorder
activate CellPanel
CellPanel --> MapPanel
deactivate CellPanel
MapPanel --> MainFrame
deactivate MapPanel
MainFrame -> MainFrame : update
activate MainFrame
MainFrame -> MapPanel : printMap
activate MapPanel
MapPanel --> MainFrame
deactivate MapPanel
MainFrame -> InventoryPanel : update
activate InventoryPanel
InventoryPanel --> MainFrame
deactivate InventoryPanel
MainFrame --> MainFrame
deactivate MainFrame
MainFrame --> SimpleMainViewFactory
deactivate MainFrame
SimpleMainViewFactory --> GameControllerImpl
deactivate SimpleMainViewFactory
GameControllerImpl -> SimpleMainViewFactory : createMainView
activate SimpleMainViewFactory
SimpleMainViewFactory -> ConsoleView : getInstance
activate ConsoleView
ConsoleView --> SimpleMainViewFactory
deactivate ConsoleView
create MainFrame
SimpleMainViewFactory -> MainFrame : new
activate MainFrame
MainFrame -> GameManager : registerObserver
activate GameManager
GameManager -> GameManagerImpl : registerObserver
activate GameManagerImpl
GameManagerImpl --> GameManager
deactivate GameManagerImpl
GameManager --> MainFrame
deactivate GameManager
create MapPanel
MainFrame -> MapPanel : new
activate MapPanel
MapPanel -> Direction : values
activate Direction
Direction --> MapPanel
deactivate Direction
MapPanel -> CellService : canMove
activate CellService
CellService --> MapPanel
deactivate CellService
create Index
MapPanel -> Index : new
activate Index
Index --> MapPanel
deactivate Index
MapPanel -> Direction : values
activate Direction
Direction --> MapPanel
deactivate Direction
MapPanel -> CellService : canMove
activate CellService
CellService --> MapPanel
deactivate CellService
MapPanel -> Direction : opposite
activate Direction
Direction --> MapPanel
deactivate Direction
MapPanel -> CellService : canMove
activate CellService
CellService --> MapPanel
deactivate CellService
MapPanel -> CellService : canMove
activate CellService
CellService --> MapPanel
deactivate CellService
create Index
MapPanel -> Index : new
activate Index
Index --> MapPanel
deactivate Index
create CellPanel
MapPanel -> CellPanel : new
activate CellPanel
CellPanel --> MapPanel
deactivate CellPanel
MapPanel --> MainFrame
deactivate MapPanel
create InventoryPanel
MainFrame -> InventoryPanel : new
activate InventoryPanel
create CardPanel
InventoryPanel -> CardPanel : new
activate CardPanel
CardPanel --> InventoryPanel
deactivate CardPanel
InventoryPanel -> CardPanel : updateCard
activate CardPanel
CardPanel --> InventoryPanel
deactivate CardPanel
InventoryPanel --> MainFrame
deactivate InventoryPanel
create BottomPanel
MainFrame -> BottomPanel : new
activate BottomPanel
create ArrowButtonPanel
BottomPanel -> ArrowButtonPanel : new
activate ArrowButtonPanel
ArrowButtonPanel --> BottomPanel
deactivate ArrowButtonPanel
BottomPanel -> BottomPanel : λ→
activate BottomPanel
BottomPanel -> GameController : rollDice
activate GameController
GameController -> GameControllerImpl : rollDice
activate GameControllerImpl
GameControllerImpl -> GameManager : rollDice
activate GameManager
GameManager -> GameManagerImpl : rollDice
activate GameManagerImpl
GameManagerImpl -> Dice : roll
activate Dice
Dice --> GameManagerImpl
deactivate Dice
GameManagerImpl --> GameManager
deactivate GameManagerImpl
GameManager --> GameControllerImpl
deactivate GameManager
GameControllerImpl -> MainView : alertMessage
activate MainView
MainView -> MainFrame : alertMessage
activate MainFrame
MainFrame --> MainView
deactivate MainFrame
MainView --> GameControllerImpl
deactivate MainView
GameControllerImpl -> GameManager : endTurn
activate GameManager
GameManager -> GameManagerImpl : endTurn
activate GameManagerImpl
GameManagerImpl -> Player : hasWon
activate Player
Player --> GameManagerImpl
deactivate Player
GameManagerImpl --> GameManager
deactivate GameManagerImpl
GameManager --> GameControllerImpl
deactivate GameManager
GameControllerImpl -> MainView : alertMessage
activate MainView
MainView -> MainFrame : alertMessage
activate MainFrame
MainFrame --> MainView
deactivate MainFrame
MainView --> GameControllerImpl
deactivate MainView
GameControllerImpl --> GameController
deactivate GameControllerImpl
GameController --> BottomPanel
deactivate GameController
BottomPanel --> BottomPanel
deactivate BottomPanel
BottomPanel -> BottomPanel : λ→
activate BottomPanel
BottomPanel -> GameController : restTurn
activate GameController
GameController -> GameControllerImpl : restTurn
activate GameControllerImpl
GameControllerImpl -> GameManager : restTurn
activate GameManager
GameManager -> GameManagerImpl : restTurn
activate GameManagerImpl
GameManagerImpl -> Player : hasBridge
activate Player
Player --> GameManagerImpl
deactivate Player
GameManagerImpl -> GameManagerImpl : endTurn
activate GameManagerImpl
GameManagerImpl -> Player : hasWon
activate Player
Player --> GameManagerImpl
deactivate Player
GameManagerImpl --> GameManagerImpl
deactivate GameManagerImpl
GameManagerImpl --> GameManager
deactivate GameManagerImpl
GameManager --> GameControllerImpl
deactivate GameManager
GameControllerImpl -> MainView : alertMessage
activate MainView
MainView -> MainFrame : alertMessage
activate MainFrame
MainFrame --> MainView
deactivate MainFrame
MainView --> GameControllerImpl
deactivate MainView
GameControllerImpl -> MainView : alertMessage
activate MainView
MainView -> MainFrame : alertMessage
activate MainFrame
MainFrame --> MainView
deactivate MainFrame
MainView --> GameControllerImpl
deactivate MainView
GameControllerImpl --> GameController
deactivate GameControllerImpl
GameController --> BottomPanel
deactivate GameController
BottomPanel --> BottomPanel
deactivate BottomPanel
BottomPanel --> MainFrame
deactivate BottomPanel
MainFrame -> MapPanel : printMap
activate MapPanel
MapPanel -> CellPanel : deletePlayer
activate CellPanel
CellPanel --> MapPanel
deactivate CellPanel
MapPanel -> CellPanel : setBorder
activate CellPanel
CellPanel --> MapPanel
deactivate CellPanel
MapPanel -> CellService : moveBridge
activate CellService
CellService --> MapPanel
deactivate CellService
create Index
MapPanel -> Index : new
activate Index
Index --> MapPanel
deactivate Index
MapPanel -> CellPanel : deleteGraphics
activate CellPanel
CellPanel --> MapPanel
deactivate CellPanel
MapPanel -> CellPanel : setBorder
activate CellPanel
CellPanel --> MapPanel
deactivate CellPanel
MapPanel --> MainFrame
deactivate MapPanel
MainFrame -> MainFrame : update
activate MainFrame
MainFrame -> MapPanel : printMap
activate MapPanel
MapPanel --> MainFrame
deactivate MapPanel
MainFrame -> InventoryPanel : update
activate InventoryPanel
InventoryPanel --> MainFrame
deactivate InventoryPanel
MainFrame --> MainFrame
deactivate MainFrame
MainFrame --> SimpleMainViewFactory
deactivate MainFrame
SimpleMainViewFactory --> GameControllerImpl
deactivate SimpleMainViewFactory
GameControllerImpl --> GameController
deactivate GameControllerImpl
GameController --> StartView
deactivate GameController
StartView --> StartView
deactivate StartView
StartView -> StartView : λ→
activate StartView
StartView -> GameController : startGame
activate GameController
GameController -> GameControllerImpl : startGame
activate GameControllerImpl
GameControllerImpl -> GameManager : initialize
activate GameManager
GameManager -> GameManagerImpl : initialize
activate GameManagerImpl
GameManagerImpl -> GameManagerImpl : initialize
activate GameManagerImpl
GameManagerImpl -> MapFileManager : evaluateFile
activate MapFileManager
MapFileManager -> MapFileManager : λ→
activate MapFileManager
MapFileManager -> BridgeMap : makeCell
activate BridgeMap
create StartCell
BridgeMap -> StartCell : new
activate StartCell
StartCell --> BridgeMap
deactivate StartCell
BridgeMap -> Direction : getDirectionByChar
activate Direction
Direction --> BridgeMap
deactivate Direction
BridgeMap -> Direction : getDirectionByChar
activate Direction
Direction --> BridgeMap
deactivate Direction
BridgeMap -> Direction : opposite
activate Direction
Direction --> BridgeMap
deactivate Direction
create Cell
BridgeMap -> Cell : new
activate Cell
Cell --> BridgeMap
deactivate Cell
create BridgeCell
BridgeMap -> BridgeCell : new
activate BridgeCell
BridgeCell --> BridgeMap
deactivate BridgeCell
create BridgeCell
BridgeMap -> BridgeCell : new
activate BridgeCell
BridgeCell --> BridgeMap
deactivate BridgeCell
BridgeMap -> CellService : connectCell
activate CellService
CellService --> BridgeMap
deactivate CellService
BridgeMap -> CellService : connectCell
activate CellService
CellService --> BridgeMap
deactivate CellService
create CardCell
BridgeMap -> CardCell : new
activate CardCell
CardCell --> BridgeMap
deactivate CardCell
create CardCell
BridgeMap -> CardCell : new
activate CardCell
CardCell --> BridgeMap
deactivate CardCell
create CardCell
BridgeMap -> CardCell : new
activate CardCell
CardCell --> BridgeMap
deactivate CardCell
create EndCell
BridgeMap -> EndCell : new
activate EndCell
EndCell --> BridgeMap
deactivate EndCell
BridgeMap -> CellService : connectCell
activate CellService
CellService --> BridgeMap
deactivate CellService
BridgeMap -> CellService : connectCell
activate CellService
CellService --> BridgeMap
deactivate CellService
BridgeMap -> CellService : connectCell
activate CellService
CellService --> BridgeMap
deactivate CellService
BridgeMap -> Direction : getDirectionByChar
activate Direction
Direction --> BridgeMap
deactivate Direction
BridgeMap --> MapFileManager
deactivate BridgeMap
MapFileManager --> MapFileManager
deactivate MapFileManager
MapFileManager --> GameManagerImpl
deactivate MapFileManager
create Player
GameManagerImpl -> Player : new
activate Player
Player --> GameManagerImpl
deactivate Player
GameManagerImpl --> GameManagerImpl
deactivate GameManagerImpl
GameManagerImpl --> GameManager
deactivate GameManagerImpl
GameManager --> GameControllerImpl
deactivate GameManager
GameControllerImpl -> SimpleMainViewFactory : createMainView
activate SimpleMainViewFactory
SimpleMainViewFactory -> ConsoleView : getInstance
activate ConsoleView
ConsoleView --> SimpleMainViewFactory
deactivate ConsoleView
create MainFrame
SimpleMainViewFactory -> MainFrame : new
activate MainFrame
MainFrame -> GameManager : registerObserver
activate GameManager
GameManager -> GameManagerImpl : registerObserver
activate GameManagerImpl
GameManagerImpl --> GameManager
deactivate GameManagerImpl
GameManager --> MainFrame
deactivate GameManager
create MapPanel
MainFrame -> MapPanel : new
activate MapPanel
MapPanel -> Direction : values
activate Direction
Direction --> MapPanel
deactivate Direction
MapPanel -> CellService : canMove
activate CellService
CellService --> MapPanel
deactivate CellService
create Index
MapPanel -> Index : new
activate Index
Index --> MapPanel
deactivate Index
MapPanel -> Direction : values
activate Direction
Direction --> MapPanel
deactivate Direction
MapPanel -> CellService : canMove
activate CellService
CellService --> MapPanel
deactivate CellService
MapPanel -> Direction : opposite
activate Direction
Direction --> MapPanel
deactivate Direction
MapPanel -> CellService : canMove
activate CellService
CellService --> MapPanel
deactivate CellService
MapPanel -> CellService : canMove
activate CellService
CellService --> MapPanel
deactivate CellService
create Index
MapPanel -> Index : new
activate Index
Index --> MapPanel
deactivate Index
create CellPanel
MapPanel -> CellPanel : new
activate CellPanel
CellPanel --> MapPanel
deactivate CellPanel
MapPanel --> MainFrame
deactivate MapPanel
create InventoryPanel
MainFrame -> InventoryPanel : new
activate InventoryPanel
create CardPanel
InventoryPanel -> CardPanel : new
activate CardPanel
CardPanel --> InventoryPanel
deactivate CardPanel
InventoryPanel -> CardPanel : updateCard
activate CardPanel
CardPanel --> InventoryPanel
deactivate CardPanel
InventoryPanel --> MainFrame
deactivate InventoryPanel
create BottomPanel
MainFrame -> BottomPanel : new
activate BottomPanel
create ArrowButtonPanel
BottomPanel -> ArrowButtonPanel : new
activate ArrowButtonPanel
ArrowButtonPanel --> BottomPanel
deactivate ArrowButtonPanel
BottomPanel -> BottomPanel : λ→
activate BottomPanel
BottomPanel -> GameController : rollDice
activate GameController
GameController -> GameControllerImpl : rollDice
activate GameControllerImpl
GameControllerImpl -> GameManager : rollDice
activate GameManager
GameManager -> GameManagerImpl : rollDice
activate GameManagerImpl
GameManagerImpl -> Dice : roll
activate Dice
Dice --> GameManagerImpl
deactivate Dice
GameManagerImpl --> GameManager
deactivate GameManagerImpl
GameManager --> GameControllerImpl
deactivate GameManager
GameControllerImpl -> MainView : alertMessage
activate MainView
MainView -> MainFrame : alertMessage
activate MainFrame
MainFrame --> MainView
deactivate MainFrame
MainView --> GameControllerImpl
deactivate MainView
GameControllerImpl -> GameManager : endTurn
activate GameManager
GameManager -> GameManagerImpl : endTurn
activate GameManagerImpl
GameManagerImpl -> Player : hasWon
activate Player
Player --> GameManagerImpl
deactivate Player
GameManagerImpl --> GameManager
deactivate GameManagerImpl
GameManager --> GameControllerImpl
deactivate GameManager
GameControllerImpl -> MainView : alertMessage
activate MainView
MainView -> MainFrame : alertMessage
activate MainFrame
MainFrame --> MainView
deactivate MainFrame
MainView --> GameControllerImpl
deactivate MainView
GameControllerImpl --> GameController
deactivate GameControllerImpl
GameController --> BottomPanel
deactivate GameController
BottomPanel --> BottomPanel
deactivate BottomPanel
BottomPanel -> BottomPanel : λ→
activate BottomPanel
BottomPanel -> GameController : restTurn
activate GameController
GameController -> GameControllerImpl : restTurn
activate GameControllerImpl
GameControllerImpl -> GameManager : restTurn
activate GameManager
GameManager -> GameManagerImpl : restTurn
activate GameManagerImpl
GameManagerImpl -> Player : hasBridge
activate Player
Player --> GameManagerImpl
deactivate Player
GameManagerImpl -> GameManagerImpl : endTurn
activate GameManagerImpl
GameManagerImpl -> Player : hasWon
activate Player
Player --> GameManagerImpl
deactivate Player
GameManagerImpl --> GameManagerImpl
deactivate GameManagerImpl
GameManagerImpl --> GameManager
deactivate GameManagerImpl
GameManager --> GameControllerImpl
deactivate GameManager
GameControllerImpl -> MainView : alertMessage
activate MainView
MainView -> MainFrame : alertMessage
activate MainFrame
MainFrame --> MainView
deactivate MainFrame
MainView --> GameControllerImpl
deactivate MainView
GameControllerImpl -> MainView : alertMessage
activate MainView
MainView -> MainFrame : alertMessage
activate MainFrame
MainFrame --> MainView
deactivate MainFrame
MainView --> GameControllerImpl
deactivate MainView
GameControllerImpl --> GameController
deactivate GameControllerImpl
GameController --> BottomPanel
deactivate GameController
BottomPanel --> BottomPanel
deactivate BottomPanel
BottomPanel --> MainFrame
deactivate BottomPanel
MainFrame -> MapPanel : printMap
activate MapPanel
MapPanel -> CellPanel : deletePlayer
activate CellPanel
CellPanel --> MapPanel
deactivate CellPanel
MapPanel -> CellPanel : setBorder
activate CellPanel
CellPanel --> MapPanel
deactivate CellPanel
MapPanel -> CellService : moveBridge
activate CellService
CellService --> MapPanel
deactivate CellService
create Index
MapPanel -> Index : new
activate Index
Index --> MapPanel
deactivate Index
MapPanel -> CellPanel : deleteGraphics
activate CellPanel
CellPanel --> MapPanel
deactivate CellPanel
MapPanel -> CellPanel : setBorder
activate CellPanel
CellPanel --> MapPanel
deactivate CellPanel
MapPanel --> MainFrame
deactivate MapPanel
MainFrame -> MainFrame : update
activate MainFrame
MainFrame -> MapPanel : printMap
activate MapPanel
MapPanel --> MainFrame
deactivate MapPanel
MainFrame -> InventoryPanel : update
activate InventoryPanel
InventoryPanel --> MainFrame
deactivate InventoryPanel
MainFrame --> MainFrame
deactivate MainFrame
MainFrame --> SimpleMainViewFactory
deactivate MainFrame
SimpleMainViewFactory --> GameControllerImpl
deactivate SimpleMainViewFactory
GameControllerImpl -> SimpleMainViewFactory : createMainView
activate SimpleMainViewFactory
SimpleMainViewFactory -> ConsoleView : getInstance
activate ConsoleView
ConsoleView --> SimpleMainViewFactory
deactivate ConsoleView
create MainFrame
SimpleMainViewFactory -> MainFrame : new
activate MainFrame
MainFrame -> GameManager : registerObserver
activate GameManager
GameManager -> GameManagerImpl : registerObserver
activate GameManagerImpl
GameManagerImpl --> GameManager
deactivate GameManagerImpl
GameManager --> MainFrame
deactivate GameManager
create MapPanel
MainFrame -> MapPanel : new
activate MapPanel
MapPanel -> Direction : values
activate Direction
Direction --> MapPanel
deactivate Direction
MapPanel -> CellService : canMove
activate CellService
CellService --> MapPanel
deactivate CellService
create Index
MapPanel -> Index : new
activate Index
Index --> MapPanel
deactivate Index
MapPanel -> Direction : values
activate Direction
Direction --> MapPanel
deactivate Direction
MapPanel -> CellService : canMove
activate CellService
CellService --> MapPanel
deactivate CellService
MapPanel -> Direction : opposite
activate Direction
Direction --> MapPanel
deactivate Direction
MapPanel -> CellService : canMove
activate CellService
CellService --> MapPanel
deactivate CellService
MapPanel -> CellService : canMove
activate CellService
CellService --> MapPanel
deactivate CellService
create Index
MapPanel -> Index : new
activate Index
Index --> MapPanel
deactivate Index
create CellPanel
MapPanel -> CellPanel : new
activate CellPanel
CellPanel --> MapPanel
deactivate CellPanel
MapPanel --> MainFrame
deactivate MapPanel
create InventoryPanel
MainFrame -> InventoryPanel : new
activate InventoryPanel
create CardPanel
InventoryPanel -> CardPanel : new
activate CardPanel
CardPanel --> InventoryPanel
deactivate CardPanel
InventoryPanel -> CardPanel : updateCard
activate CardPanel
CardPanel --> InventoryPanel
deactivate CardPanel
InventoryPanel --> MainFrame
deactivate InventoryPanel
create BottomPanel
MainFrame -> BottomPanel : new
activate BottomPanel
create ArrowButtonPanel
BottomPanel -> ArrowButtonPanel : new
activate ArrowButtonPanel
ArrowButtonPanel --> BottomPanel
deactivate ArrowButtonPanel
BottomPanel -> BottomPanel : λ→
activate BottomPanel
BottomPanel -> GameController : rollDice
activate GameController
GameController -> GameControllerImpl : rollDice
activate GameControllerImpl
GameControllerImpl -> GameManager : rollDice
activate GameManager
GameManager -> GameManagerImpl : rollDice
activate GameManagerImpl
GameManagerImpl -> Dice : roll
activate Dice
Dice --> GameManagerImpl
deactivate Dice
GameManagerImpl --> GameManager
deactivate GameManagerImpl
GameManager --> GameControllerImpl
deactivate GameManager
GameControllerImpl -> MainView : alertMessage
activate MainView
MainView -> MainFrame : alertMessage
activate MainFrame
MainFrame --> MainView
deactivate MainFrame
MainView --> GameControllerImpl
deactivate MainView
GameControllerImpl -> GameManager : endTurn
activate GameManager
GameManager -> GameManagerImpl : endTurn
activate GameManagerImpl
GameManagerImpl -> Player : hasWon
activate Player
Player --> GameManagerImpl
deactivate Player
GameManagerImpl --> GameManager
deactivate GameManagerImpl
GameManager --> GameControllerImpl
deactivate GameManager
GameControllerImpl -> MainView : alertMessage
activate MainView
MainView -> MainFrame : alertMessage
activate MainFrame
MainFrame --> MainView
deactivate MainFrame
MainView --> GameControllerImpl
deactivate MainView
GameControllerImpl --> GameController
deactivate GameControllerImpl
GameController --> BottomPanel
deactivate GameController
BottomPanel --> BottomPanel
deactivate BottomPanel
BottomPanel -> BottomPanel : λ→
activate BottomPanel
BottomPanel -> GameController : restTurn
activate GameController
GameController -> GameControllerImpl : restTurn
activate GameControllerImpl
GameControllerImpl -> GameManager : restTurn
activate GameManager
GameManager -> GameManagerImpl : restTurn
activate GameManagerImpl
GameManagerImpl -> Player : hasBridge
activate Player
Player --> GameManagerImpl
deactivate Player
GameManagerImpl -> GameManagerImpl : endTurn
activate GameManagerImpl
GameManagerImpl -> Player : hasWon
activate Player
Player --> GameManagerImpl
deactivate Player
GameManagerImpl --> GameManagerImpl
deactivate GameManagerImpl
GameManagerImpl --> GameManager
deactivate GameManagerImpl
GameManager --> GameControllerImpl
deactivate GameManager
GameControllerImpl -> MainView : alertMessage
activate MainView
MainView -> MainFrame : alertMessage
activate MainFrame
MainFrame --> MainView
deactivate MainFrame
MainView --> GameControllerImpl
deactivate MainView
GameControllerImpl -> MainView : alertMessage
activate MainView
MainView -> MainFrame : alertMessage
activate MainFrame
MainFrame --> MainView
deactivate MainFrame
MainView --> GameControllerImpl
deactivate MainView
GameControllerImpl --> GameController
deactivate GameControllerImpl
GameController --> BottomPanel
deactivate GameController
BottomPanel --> BottomPanel
deactivate BottomPanel
BottomPanel --> MainFrame
deactivate BottomPanel
MainFrame -> MapPanel : printMap
activate MapPanel
MapPanel -> CellPanel : deletePlayer
activate CellPanel
CellPanel --> MapPanel
deactivate CellPanel
MapPanel -> CellPanel : setBorder
activate CellPanel
CellPanel --> MapPanel
deactivate CellPanel
MapPanel -> CellService : moveBridge
activate CellService
CellService --> MapPanel
deactivate CellService
create Index
MapPanel -> Index : new
activate Index
Index --> MapPanel
deactivate Index
MapPanel -> CellPanel : deleteGraphics
activate CellPanel
CellPanel --> MapPanel
deactivate CellPanel
MapPanel -> CellPanel : setBorder
activate CellPanel
CellPanel --> MapPanel
deactivate CellPanel
MapPanel --> MainFrame
deactivate MapPanel
MainFrame -> MainFrame : update
activate MainFrame
MainFrame -> MapPanel : printMap
activate MapPanel
MapPanel --> MainFrame
deactivate MapPanel
MainFrame -> InventoryPanel : update
activate InventoryPanel
InventoryPanel --> MainFrame
deactivate InventoryPanel
MainFrame --> MainFrame
deactivate MainFrame
MainFrame --> SimpleMainViewFactory
deactivate MainFrame
SimpleMainViewFactory --> GameControllerImpl
deactivate SimpleMainViewFactory
GameControllerImpl --> GameController
deactivate GameControllerImpl
GameController --> StartView
deactivate GameController
StartView --> StartView
deactivate StartView
StartView -> StartView : λ→
activate StartView
StartView --> StartView
deactivate StartView
StartView --> GameControllerImpl
deactivate StartView
return
@enduml